JNG-4505 Release judo meta rdbms
BlackBeltTechnology/judo-meta-rdbms pull request #55
Opened 2023-02-28 14:35 UTC by gaborflorian

2023-02-28 14:56 UTC, noherczeg approved these changes

2023-02-28 22:16 UTC, bencegelei requested changes

2023-02-28 22:16 UTC, bencegelei commented on pom.xml
> +				<version>1.2.11</version>
Is this version downgrade intentional?

2023-03-01 09:38 UTC, gaborflorian commented on pom.xml
> +				<version>1.2.11</version>
Requested by Robert

2023-03-01 10:10 UTC, robertcsakany approved these changes

2023-03-01 11:53 UTC, bencegelei approved these changes

2023-03-09 10:25 UTC, merged